blank_issues_enabled: true
contact_links:
  - name: SayaProject Telegram
    url: https://t.me/SayaProject
    about: Follow official project updates.
  - name: Direct Telegram Contact
    url: https://t.me/Sayafq
    about: Contact SayaProject directly.
  - name: GitHub Support
    url: https://github.com/IFlexElite
    about: GitHub support profile for SayaProject.